import pygame
from class_Button import Button
class RegleJeux:
    def __init__(self):
        self.height = 568
        self.width = 960
        self.bg = pygame.image.load("images/backgrounds/bg6.jpg").convert()
        self.clavier = pygame.image.load("images/boutons/clavier.jpg")
        self.fleche= pygame.image.load("images/boutons/fleche.jpg")
        self.policeRegle = pygame.font.Font(None,35)
        self.policetexte = pygame.font.Font(None,22)
        self.texte0= self.policeRegle.render('Régle du jeux',True,(96,76,141))
        self.texte1 = self.policetexte.render('Objectif',True,(255,0,0))
        self.texte2= self.policetexte.render('Durant cette partie Vous devez evitez les obstacles ',True,(0,0,0))
        self.texte3= self.policetexte.render('crées par les effets de la pollutions.Votre objectif',True,(0,0,0))
        self.texte4= self.policetexte.render('est de répondre correctement aux questions du gardient',True,(0,0,0))
        self.texte5= self.policetexte.render('de la nature.Ce personnage est essentiel dans la partie.',True,(0,0,0))
        self.texte6= self.policetexte.render('Il permet de vous transmettre son savoir pour dépolluer',True,(0,0,0))
        self.texte7= self.policetexte.render('l''air À chaque ville le gardien vous pose une question.',True,(0,0,0))
        self.texte8= self.policetexte.render('Si vous trouvez la réponse il vous transmet une bonbonne',True,(0,0,0))
        self.texte9= self.policetexte.render('d''oxygène nécessaire pour votre survie.',True,(0,0,0))
        self.texte10= self.policetexte.render('Vous devrez faire gaffe de vigilance car votre vie diminue',True,(0,0,0))
        self.texte11= self.policetexte.render('progressivement au cours du temps vous devez manier rapidité',True,(0,0,0))
        self.texte12= self.policetexte.render('et réactivité afin d''ateindre la dernière ville sinon ',True,(0,0,0))
        self.texte12= self.policetexte.render('vous mourriez asphyxé.Bonne chance ',True,(0,0,0))
        self.texte13= self.policetexte.render('Commande',True,(255,0,0))
        self.texte14= self.policetexte.render('La touche espace permet de faire sauter le joueur en',True,(0,0,0))
        self.texte15= self.policetexte.render('l''air dans le but d''éviter les diffèrents obstacles',True,(0,0,0))
        self.texte16= self.policetexte.render('Les touche flèches permettent de déplacer le joueur',True,(0,0,0))
        self.texte17= self.policetexte.render('à gauche et à droite pour traverser les villes',True,(0,0,0))
        self.buttonBack = Button(160,10,"images/boutons/boutonRetourAccueil.gif")

    def afficher(self,surface):
        pygame.display.set_caption("Règle de jeux")
        surface.blit(self.bg,(0,0))
        surface.blit(self.buttonBack.image,(self.buttonBack.rect.x,self.buttonBack.rect.y))
        surface.blit(self.clavier,(580,120))
        surface.blit(self.fleche,(680,350))

        surface.blit(self.texte0,(400,10))
        surface.blit(self.texte1,(170,60))
        surface.blit(self.texte2,(40,120))
        surface.blit(self.texte3,(40,150))
        surface.blit(self.texte4,(40,180))
        surface.blit(self.texte5,(40,210))
        surface.blit(self.texte6,(40,240))
        surface.blit(self.texte7,(40,270))
        surface.blit(self.texte8,(40,300))
        surface.blit(self.texte9,(40,330))
        surface.blit(self.texte10,(40,360))
        surface.blit(self.texte11,(40,390))
        surface.blit(self.texte12,(40,420))
        surface.blit(self.texte13,(700,60))
        surface.blit(self.texte14,(580,300))
        surface.blit(self.texte15,(580,330))
        surface.blit(self.texte16,(580,490))
        surface.blit(self.texte17,(580,510))

        pygame.display.update()
