import pygame
from class_Button import Button
class RegleJeux:
    def __init__(self):
        self.height = 568
        self.width = 960
        self.bg = pygame.image.load("images/backgrounds/bg6.jpg").convert()
        self.clavier = pygame.image.load("images/boutons/clavier.jpg")
        self.fleche= pygame.image.load("images/boutons/fleche.jpg")
        self.policeRegle = pygame.font.Font(None,35)
        self.policeTexte = pygame.font.Font(None,22)
        self.texte0=self.policeRegle.render('Rêgles du jeu',True,(96,76,141))
        self.texte1=self.policeTexte.render('Objectif :',True,(255,0,0))
        self.texte2=self.policeTexte.render('Durant cette partie vous devez éviter les obstacles',True,(0,0,0))
        self.texte3=self.policeTexte.render('créés par les effets de la pollution. Votre objectif',True,(0,0,0))
        self.texte4=self.policeTexte.render('est de répondre correctement aux questions du gardient',True,(0,0,0))
        self.texte5=self.policeTexte.render('de la nature. Ce personnage est essentiel dans la partie.',True,(0,0,0))
        self.texte6=self.policeTexte.render('Il permet de vous transmettre son savoir pour dépolluer',True,(0,0,0))
        self.texte7=self.policeTexte.render("l'air. À chaque ville le gardien vous pose une question.",True,(0,0,0))
        self.texte8=self.policeTexte.render('Si vous trouvez la réponse il vous transmet une bonbonne',True,(0,0,0))
        self.texte9=self.policeTexte.render("d'oxygène nécessaire pour votre survie.",True,(0,0,0))
        self.texte10=self.policeTexte.render('Vous devrez faire preuve de vigilance car votre vie diminue',True,(0,0,0))
        self.texte11=self.policeTexte.render('progressivement au cours du temps. Vous devez allier rapidité',True,(0,0,0))
        self.texte111=self.policeTexte.render("et réactivité afin d'atteindre la dernière ville.",True,(0,0,0))
        self.texte12=self.policeTexte.render('Dans le cas contraire vous mourrez asphyxié.',True,(0,0,0))
        self.texte121=self.policeTexte.render('Bonne chance !',True,(0,0,0))
        self.texte13=self.policeTexte.render('Commande :',True,(255,0,0))
        self.texte14=self.policeTexte.render('La touche ESPACE permet de faire sauter le joueur en',True,(0,0,0))
        self.texte15=self.policeTexte.render("l'air dans le but d'éviter les differents obstacles.",True,(0,0,0))
        self.texte16=self.policeTexte.render('Les flèches directionelles permettent de déplacer le joueur',True,(0,0,0))
        self.texte17=self.policeTexte.render('à gauche et à droite pour traverser les villes.',True,(0,0,0))
        self.buttonBack = Button(150,10,"images/boutons/boutonRetourAccueil.gif")

    def afficher(self,surface):
        pygame.display.set_caption("Règle de jeux")
        surface.blit(self.bg,(0,0))
        surface.blit(self.buttonBack.image,(self.buttonBack.rect.x,self.buttonBack.rect.y))
        surface.blit(self.clavier,(580,120))
        surface.blit(self.fleche,(680,350))
        surface.blit(self.clavier,(580,120))
        surface.blit(self.fleche,(680,350))

        surface.blit(self.texte0,(400,10))
        surface.blit(self.texte1,(170,60))
        surface.blit(self.texte2,(40,120))
        surface.blit(self.texte3,(40,150))
        surface.blit(self.texte4,(40,180))
        surface.blit(self.texte5,(40,210))
        surface.blit(self.texte6,(40,240))
        surface.blit(self.texte7,(40,270))
        surface.blit(self.texte8,(40,300))
        surface.blit(self.texte9,(40,330))
        surface.blit(self.texte10,(40,360))
        surface.blit(self.texte11,(40,390))
        surface.blit(self.texte111,(40,420))
        surface.blit(self.texte12,(40,450))
        surface.blit(self.texte121,(40,480))
        surface.blit(self.texte13,(700,60))
        surface.blit(self.texte14,(580,300))
        surface.blit(self.texte15,(580,330))
        surface.blit(self.texte16,(580,490))
        surface.blit(self.texte17,(580,510))
        pygame.display.update()
